runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
  BUCKET_NAME: "react-sandbox-333"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /
  static_dir: dist 

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

